name: Test with booleans

on:
  workflow_dispatch:
    inputs:
      dont_echo:
        required: false
        type: boolean

jobs:
  my-test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Before greeting"
      - run: echo "Hello, world!"
        if: inputs.dont_echo == 'false'
      - run: echo "After greeting"
