name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [windows-2019]

    steps:
    - name: Show directory in cmd
      run: |
        cd
        dir \
        dir \a
        mkdir \usr
        mkdir \usr\local
        mkdir \usr\local\zeek
      shell: cmd

    - name: Show directory in sh
      run: |
        pwd
        ls -l /
        ls -l /usr
        ls -l /usr/local
      shell: sh
