name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [windows-2019]

    steps:
    - name: Show directory in cmd
      run: |
        cd
        dir \
        dir \a
        mkdir \usr
        mkdir \usr\local
        mkdir \usr\local\zeek
        cd \usr\local\zeek
        type "hello" > hello.txt
        cd
      shell: cmd

    - name: Show directory in sh
      run: |
        pwd
        echo "Contents of /"
        ls -l /
        echo "Contents of /usr"
        ls -l /usr
        echo "Conents of /d"
        ls -l /d
        echo "Contents of /d/usr"
        ls -l /d/usr
        echo "Conents of /d/usr/local"
        ls -l /d/usr/local
        echo "Contents of /d/usr/local/zeek"
        ls -l /d/usr/local/zeek
      shell: sh
