name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [windows-2019]

    steps:
    - name: Show directory in cmd
      run: |
        cd
        dir \
        dir \a
        mkdir \usr
        mkdir \usr\local
        mkdir \usr\local\zeek
        cd \usr\local\zeek
        cd
      shell: cmd

    - name: Show directory in sh
      run: |
        pwd
        echo "Contents of /"
        ls -l /
        echo "Contents of /usr"
        ls -l /usr
        echo "Contents of /usr/local"
        ls -l /usr/local
        echo "Conents of /d"
        ls -l /d
      shell: sh
