name: Platforms shell test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04, windows-2019]
#        platform: [macos-12, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run the test
      run: ./foo.sh
      shell: bash
