name: Platforms shell test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [macos-12, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Run the test
      run: ./foo.sh
      shell: sh
