name: Upload artifact test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [windows-2019]

    steps:
    - name: Make some files
      run: |
        mkdir zeek
        cd zeek
        echo "hello" > hello.txt
        echo "goodbye" > goodbye.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      path: zeek
